export const SQLITE_QUEUE_CONFIG_TOKEN = 'SQLITE_QUEUE_CONFIG_TOKEN'
export const SQLITE_QUEUE_HANDLER_TOKEN = 'SQLITE_QUEUE_HANDLER_TOKEN'
export const SQLITE_QUEUE_EVENT_TOKEN = 'SQLITE_QUEUE_EVENT_TOKEN'
export const SQLITE_QUEUE_PROCESS_TOKEN = 'SQLITE_QUEUE_PROCESS_TOKEN'

export const DEFAULT_CONNECTION_NAME = 'DEFAULT_CONNECTION'
export const DEFAULT_QUEUE_NAME = 'DEFAULT_QUEUE'
