export const SQLITE_QUEUE_CONFIG_TOKEN = 'SQLITE_QUEUE_CONFIG_TOKEN'
export const SQLITE_QUEUE_HANDLER_TOKEN = 'SQLITE_QUEUE_HANDLER_TOKEN'
export const SQLITE_QUEUE_EVENT_TOKEN = 'SQLITE_QUEUE_EVENT_TOKEN'
export const SQLITE_QUEUE_PROCESS_TOKEN = 'SQLITE_QUEUE_PROCESS_TOKEN'
export const SQLITE_QUEUE_CONNECTION_NAME_TOKEN = 'SQLITE_QUEUE_CONNECTION_NAME_TOKEN'

export const SQLITE_QUEUE_DEFAULT_CONNECTION_NAME = 'SQLITE_QUEUE_DEFAULT_CONNECTION_NAME'
export const SQLITE_QUEUE_DEFAULT_QUEUE_NAME = 'SQLITE_QUEUE_DEFAULT_QUEUE_NAME'

export const SQLITE_QUEUE_DEFAULT_JOB_FAIL_ON_STALLED = false
export const SQLITE_QUEUE_DEFAULT_JOB_TIMEOUT = 30000
export const SQLITE_QUEUE_DEFAULT_JOB_RETRIES = 0
